#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules/ipull/dist/cli/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules/ipull/dist/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules/ipull/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules/ipull/dist/cli/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules/ipull/dist/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules/ipull/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/ipull@3.9.5/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../ipull@3.9.5/node_modules/ipull/dist/cli/cli.js" "$@"
else
  exec node  "$basedir/../../../../../ipull@3.9.5/node_modules/ipull/dist/cli/cli.js" "$@"
fi
