#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules/node-llama-cpp/dist/cli/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules/node-llama-cpp/dist/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules/node-llama-cpp/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules/node-llama-cpp/dist/cli/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules/node-llama-cpp/dist/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules/node-llama-cpp/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-llama-cpp@3.15.1_typescript@5.9.3/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../dist/cli/cli.js" "$@"
else
  exec node  "$basedir/../../dist/cli/cli.js" "$@"
fi
