#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-downloader-helper@2.1.10/node_modules/node-downloader-helper/bin/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-downloader-helper@2.1.10/node_modules/node-downloader-helper/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-downloader-helper@2.1.10/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-downloader-helper@2.1.10/node_modules/node-downloader-helper/bin/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-downloader-helper@2.1.10/node_modules/node-downloader-helper/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node-downloader-helper@2.1.10/node_modules:/Users/maxpetrusenko/Desktop/Projects/OpenClaw/oss/openclaw/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../node-downloader-helper@2.1.10/node_modules/node-downloader-helper/bin/ndh" "$@"
else
  exec node  "$basedir/../../../../../../node-downloader-helper@2.1.10/node_modules/node-downloader-helper/bin/ndh" "$@"
fi
